### ISSUE TITLE
mute and ignore not working

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [fwouts/prmonitor#1048]
Selecting an option to mute or ignore does not seem to remove the "Incoming PRs". I'm on current version 0.10.4 and Chrome Version 104.0.5112.101 (Official Build) (arm64)

**Comment by fwouts** [comment]
Thanks for the bug report! It appears that was caused by a library upgrade. I'll see if that can be fixed easily.

(I didn't notice this earlier because I don't use the extension anymore since I work solo)

**Comment by fwouts** [comment]
The fix has been uploaded to Chrome & Firefox extension stores, should hopefully be available in a few hours :)
