### ISSUE TITLE
My PR is marked as 'Waiting for review' despite of fulfilling merge-ability conditions.

### ISSUE THREAD

**Issue by emempi** [fwouts/prmonitor#341]
The PRs in 'My PRs' section are marked as 'Waiting for review' despite of fulfilling mergeability conditions configured for our repo:
 * having a passing review (out of at least one reviewer, which is our setting, 3 codeowners auto-added as reviewers)
 * green required CI run

If the condition is actually waiting for all reviews to complete, maybe just adding a new 'mergeable' badge based on https://developer.github.com/v3/git/#checking-mergeability-of-pull-requests would be enough.

**Comment by fwouts** [comment]
Fair feedback. Adding a tag that lets you know that the PR is mergeable should be easy. I'll look into it in the next few days :)

**Comment by fwouts** [comment]
This feature is coming soon. I do need to improve unit testing coverage before releasing the new version though. I don't fully trust this code :)

**Comment by emempi** [comment]
Thanks a lot :)

**Comment by fwouts** [comment]
This is included in v0.5.2, which was just pushed to Firefox & Chrome web stores.

**Comment by emempi** [comment]
Yup, I just noticed it, but looks like the 'mergeable' flag does not mean the thing I'd expect -- Apparently, although I still don't have any review from my reviewers (and thus, I'm blocked), the PR is marked as mergeable. I'm afraid this is just the raw merge-ability (without fixing merge conflicts) :-/

**Comment by fwouts** [comment]
That's unfortunate. By any chance would you be able to look at what GitHub's API returns for that PR? You could see that by debugging the Chrome extension's background script, or hitting the API directly yourself.

**Comment by emempi** [comment]
I had a quick look around, but couldn't find anything besides `mergeable`. I'll try to look a bit more -- there has to be something that makes the 'merge' button green :)

**Comment by emempi** [comment]
I'm still trying to get some data; I contacted github support and we'll whether there will be any useful data about this.
