### ISSUE TITLE
Draft PR status not displayed in list of PRs

### ISSUE THREAD

**Issue by teejae** [fwouts/prmonitor#398]
Having Draft status would be useful to know what PRs to review and not.

**Comment by fwouts** [comment]
Are you implying that people assign a draft PR to you, and they don't want you to review it despite having added you as a reviewer?

**Comment by tim-clipchamp** [comment]
For me, I have the use case that I review a PR, and if it needs significant changes, then author might put it back into draft state. I can then "Mute until next update by author", but if I mute _after_ their last change, but before they remove the draft state, I don't get notified. I see two good ways of this being solved for me personally:

- a "Mute until not draft" option
- considering a `draft --> not-draft` transition as an "update by author"

**Comment by fwouts** [comment]
Thanks, @tim-clipchamp. I like that second approach as I think in general people would want to be notified when the status of a PR changes from draft to not-draft. I'll try to implement it over the next few days.

**Comment by fwouts** [comment]
@tim-clipchamp I ended up option for the first approach ("Mute until draft") because there would otherwise be no way to distinguish between "I want to know about the next update to this draft" and "I want to know when this PR is no longer a draft". Release should be live some time later today :)

**Comment by tim-clipchamp** [comment]
Thanks @fwouts. I appreciate it.
