### ISSUE TITLE
Continuous Spinner - no api token prompt appears

### ISSUE THREAD

**Issue by IcyCaster** [fwouts/prmonitor#486]
I was testing out your extension and trying to run it locally when I got a continuous spinner - the GitHub prompt never loaded for me.

To confirm it wasn't just my machine I checked out a past commit `75a98fe` and the prompt appeared for me.

**Comment by fwouts** [comment]
Thanks for the bug report! This should be fixed now.

**Comment by IcyCaster** [comment]
Working now!
Thanks, and I also appreciate the great YouTube presentation about this app btw!
Clean and concise explainations!

**Comment by fwouts** [comment]
Glad to hear it. Just to clarify, what YouTube presentation are you referring to? :)
