### ISSUE TITLE
Consider removing the `-review-requested:${userLogin}` from the query to fill the list "My PRs"

### ISSUE THREAD

**Issue by sdeprez** [fwouts/prmonitor#764]
Basically remove the `-review-requested:${userLogin}` from here https://github.com/fwouts/prmonitor/blob/d1f027dd1c02ed69662648764a644a74130b8cfd/src/loading/internal/pull-requests.ts#L35 or at least make it optional. 

My usecase is the following: 
- in my organization, we use CODEOWNERS intensively along with Github teams, that way for every PR that we made, the proper team is automatically added as a reviewer
- For almost all the PRs that I made I'm also a member of the team responsible for this part of the code, which means I'm considered as a reviewer for the search API because the team is added as a reviewer
- As a consequence I don't see any of my PRs in the tab "My PRs"

Sidenote not related to this problem, but linked: is the `-commenter:${userLogin}` here on purpose too? I think I don't want to loose the PR in my tab just because I commented it no?

Screenshot of the API documentation that highlights the problem: https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests

![Screen Shot 2020-04-22 at 20 57 14](https://user-images.githubusercontent.com/4971382/80022163-eef59e80-84db-11ea-9c6d-2933e82d51cc.png)

Anyway thank for your extension, it has been a great productivity boost so far!

**Comment by fwouts** [comment]
Thanks for reporting the issue!

Just so I clarify, does this mean that all your own PRs appear in the "Incoming PRs" tab instead?

**Comment by sdeprez** [comment]
No, they appear nowhere actually!

**Comment by fwouts** [comment]
I just published the fix in v0.6.1, which should hopefully be available soon (depending on review times). Let me know how it goes!

**Comment by sdeprez** [comment]
And I confirm that it works, thanks!
