### ISSUE TITLE
Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by slaweet** [fwouts/prmonitor#768]
It would be useful to be able to connect the extension to an on-premise instance of [GitHub Enterprise](https://github.com/enterprise)

I know that another GitHub extension allows that https://github.com/sindresorhus/refined-github

BTW thanks for a great extension :1st_place_medal:

**Comment by fwouts** [comment]
Great idea!

It looks like it's almost a [one-line change](https://github.com/octokit/rest.js/issues/1010#issuecomment-420519264) if we just wanted to point PR Monitor to GitHub Enterprise instead of GitHub.

However, I imagine you'd want it to collect PRs from both GitHub and GitHub Enterprise?

Heads-up, this might be a bit tricky to do on my own as I don't have access to GitHub Enterprise. I'll probably need some help from you :)

**Comment by slaweet** [comment]
Thanks for the quick reply. 

> However, I imagine you'd want it to collect PRs from both GitHub and GitHub Enterprise?

Currently, I'm working mostly with GitHub Enterprise, so it would be enough for me :slightly_smiling_face: 

> Heads-up, this might be a bit tricky to do on my own as I don't have access to GitHub Enterprise. I'll probably need some help from you :)

I can surely help with that.

**Comment by fwouts** [comment]
Cheers!

As a first step, would you mind trying out the extension with the one-line change shown in https://github.com/fwouts/prmonitor/pull/769/commits/d0f753c18ddfe128a305ec45d9485edfec38e9ad (replacing with the correct domain for you)?

There are rudimentary instructions for building the extension locally in the README, let me know if they're insufficient :)

**Comment by slaweet** [comment]
I tried to follow the install instructions in README. The only thing that was not straight-forward for me was step 4. But Google search helped. I'd suggest to include some link like https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/ (or some other if you know a better one) into step 4 in README.

Now my problem seems to be that I don't know the GitHub API endpoint of our GitHub Enterprise instance. Given our instance is on `https://git.<my_domain>.io`, I thought the API would be on `https://api.github.<my_domain>.io` or `https://api.git.<my_domain>.io`, but there's nothing. I don't know if the address is configurable or the API can be disabled altogether. I'll ask around at work on Monday and will get back to you :slightly_smiling_face:

**Comment by fwouts** [comment]
Just a random thought. Have you tried `https://api.github.git.<my_domain>.io`?

**Comment by slaweet** [comment]
So the API endpoint turned out to be `https://git.<my_domain>.io/api/v3`.

Changing the `baseUrl` seems to work perfectly:
![Screenshot from 2020-05-04 14-17-41](https://user-images.githubusercontent.com/1254342/80965256-84652c80-8e12-11ea-99e8-06fcc340c8a9.png)

I didn't yet have a chance to see a push notification, but I assume there is no reason it wouldn't work.

This solves my situation perfectly - I can run the custom-url extension in addition to the official one connected to GitHub.com

**Comment by fwouts** [comment]
That's awesome!

It does sound like a good long-term solution... I'd assume GitHub Enterprise users are a bit more security conscious so they'd appreciate having full control of the extension's code anyway.

Let's keep this issue open, and I'll write up some documentation to make it a bit easier for others to follow your lead.

Thanks for giving it a try 🙂

**Comment by fwouts** [comment]
Instructions added in https://github.com/fwouts/prmonitor/commit/97c2e58dd60d407599a3f582dd7b70cffa06adf9, so I'll close this off. Feel free to open further issues if you find any bugs with the integration.
