### ISSUE TITLE
PRs are missing from list of incoming 

### ISSUE THREAD

**Issue by clgeoio** [fwouts/prmonitor#770]
A PR that I am assigned to is not appearing in my list of incoming PRs.
See attached screenshot.

<img width="839" alt="Screen Shot 2020-05-06 at 11 49 44 am" src="https://user-images.githubusercontent.com/37571416/81132253-18f59900-8f91-11ea-8959-21cad906203e.png">

**Comment by clgeoio** [comment]
Seems as though there was some connectivity issues with my computer. It is appear in the list now.

**Comment by fwouts** [comment]
🙂 Let me know if it occurs again. It says that it was refreshed a few seconds ago, which does seem strange.
