### ISSUE TITLE
Bitbucket Support

### ISSUE THREAD

**Issue by CSFlorin** [fwouts/prmonitor#776]
Is there any plan on adding Bitbucket support? Is there some limitation of Bitbucket's API that prevents it? Would like to know what thought has been put into it already because I'd be interested in helping with it. Cheers!

**Comment by fwouts** [comment]
Hi @CSFlorin. I don't use Bitbucket so I simply haven't explored this at all. I haven't looked at their API, I would hope it's possible :) I'd encourage you to start a fork dedicated to Bitbucket, and we can look at merging them in the future if there is a clean way to support both while keeping the codebase (and the UX) clean.
